### ISSUE TITLE
right side not working?

### ISSUE THREAD

**Issue by alifemove** [beekeeb/piantor#13]
Any debug ideas? 
The left side works just fine, and if I plug in the right side to the pc the key presses show up, but the opposite side never works. I've used two different cables to connect the two together and desoldered the TRRS Jacks and put different ones on as well.

**Comment by alifemove** [comment]
```
check continuity on TX with right side RX (as well as RX with right side TX)
```
Not sure what that means, but I was able to use the firmware with right side master and the right side worked fine, and firmware with left side master and the left side worked just fine it just can't communicated between the two sides.

Im using the picos that came with the kit and the firmware from beekeeb.

**Comment by viyoriya** [comment]
are you using qmk or kmk ?  

If you have multimeter 
      
      1. check continuity with Left side pico GP0 pin with Right side GP1  (TX => RX)
      2. check continuity with Left side pico GP1 pin with Right side GP0  (RX => TX)

      3. check TRRS each pin continuity 
               1. vcc to vcc 
               2. gnd to gnd
               3. TX to RX
               4. RX to RX

     check are you using TRRS (should have 3 black or white plastics in the plug ) or TRS

**Comment by alifemove** [comment]
```
are you using qmk or kmk ?
```
I am using the firmware that comes from the docs from beekeeb so whatever that is.

```
If you have multimeter
```
I do not, but Ive used 2 different TRRS cables and jacks and both had the same issue. Seems like the issue is in the board to me.

**Comment by viyoriya** [comment]
when its connected with TRRS right side is On or Off ? 
is the Pico green or black ? 

I guess maybe TRRS connection  or TRRS cable

**Comment by alifemove** [comment]
```
when its connected with TRRS right side is On or Off ?
```
when left side is plugged in right side is off, when right side is plugged in left side is off.
```
is the Pico green or black ?
```
green
```
I guess maybe TRRS connection or TRRS cable
```
I desoldered and resoldered with new jacks and tried a different cable, neither helped.

**Comment by viyoriya** [comment]
try re flashing  the firmware on both side  

https://docs.beekeeb.com/piantor-keyboard#precompiled-firmware

or you can compile your own firmware

for KMK -     https://github.com/KMKfw/kmk_firmware/pull/723/files
for QMK -    https://github.com/qmk/qmk_firmware/tree/master/keyboards/beekeeb/piantor

flash tool for linux  - https://github.com/raspberrypi/picotool
for windows just copy uf2 file in bootloader mode 

(if find multi meter 
   1, check voltage 3v3 out pin with any gnd pin - right side 5th pin)   
    2. TX / RX pins )

**Comment by mbetim** [comment]
@alifemove can you share how you solved this issue?

I have a similar one, but I have the WeAct RP2040, and the side that isn't directly connected to the computer light up, so both halves have power.

Here's what I've tried so far:
* Reflashing (even using the firmware to clear the flash)
* Resoldered some joints, especially the ones for the TRRS cable
* Checked the pins mentioned by @viyoriya with the multimeter, and everything seems to be fine
* Flashed the firmware that turns the right side as the master one
* Tried the keyboard on a different computer
* Built and flashed a firmware with qmk configurator

To give more context as well, the keyboard was working before. This started happening after I've (mistakenly) disconnected the TRRS cable before unplugging the USB and resoldered a socket joint that wasn't good. One event happened after the other, so I don't know which one could've caused it.

**Comment by alifemove** [comment]
@mbetim I didn't solve it. But it's a known issue that if you unplug the TRRS cable while its powered it will short out so I'd say that was it. I've spoken with Leo and he's working on a version that doesn't do that.

**Comment by danjessen** [comment]
I have this same issue. Nothing worked. Both controllers still seem to react when plugged individually. But the connection between them seems broken.

**Comment by ChristianHinge** [comment]
Same problem here and I just built the keyboard. Right and left side work independently. However, I never unplugged the TRRS cable (only plugged it in once during before power on and have never unplugged it since. So I don't know how mine could have short circuited. Both halves have 3v between right hand side pin 3 and 5. There is continuity between thr four pairs of TRRS pins. Any help would be greatly appreciated

**Comment by ChristianHinge** [comment]
I seem to have fixed the issue by resoldering the GP0->GP1 connections.

**Comment by danjessen** [comment]
I used a different controller that was a supposed clone of the pi. But turns out there are some differences. And I needed to solder a bride to make it work. This issue no longer exists in my version.
